version: '3.7'
services:
    app:
        build:
            args:
                - user=${USER}
                - uid=${UID}
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - './:/var/www/'
        ports:
          - "5173:5173"
        expose:
          - "9000"
        networks:
            - redirect
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./:/var/www
        depends_on:
            - app
        networks:
            - redirect
networks:
    redirect:
        driver: bridge
